# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Matheus Sousa
title: Técnico em Manutenção e Suporte em Informatica
email: sousamatheus994@gmail.com
website: www.github.com/matheus96s

# Social links
twitter_username: matheus96s
github_username:  matheus96s
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: _matheussousa96_
linkedin_username: matheus96s
# pinterest_username: jekyll
youtube_username: matheus96s
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Olá, meu nome é Matheus Sousa e sou Tecnico em Mantenção e Suporte em Informática. Além de técnico, também tenho experiência na criação de software e aplicativos da web. Trabalhei em várias empresas, ganhando trabalho em equipe e habilidades de liderança.
  Eu sou mais experiente em: <mark> VisualG </mark> e <mark> Dormir </mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
 Juntamente com meus interesses em informática, alguns de meus outros interesses e hobbies são:
   - Espancar Maconheiros
   - Ping-Pong
   - Tricô
   - [10 Horas de Sera que eu pego o ônibus ou compro uma goiaba] (https://www.youtube.com/watch?v=FcbsQfDQTNw)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
